### ISSUE TITLE
[tesseract-ocr] traindata for cmc7 font

### ISSUE THREAD

**Issue by haytham90-z** [DoubangoTelecom/tesseractMICR#3]
hi to all 

I want to know if anyone has the .train data file for CMC7  font, and if so,  could I get the file? 

thanx

**Comment by DoubangoTelecom** [comment]
For now only E-13B models are available. We'll add CMC-7 on our roadmap.

**Comment by haytham90-z** [comment]
Thanks for your reply ,I dont need E-13B but I need CMC-7 models because our banks cheques used CMC-7 .but I want to ask when yoy can add the CMC-7 in the roadmap , what do you mean about roadmap ? do u mean the roadmap   same the traker ?

**Comment by DoubangoTelecom** [comment]
Added on the roadmap means we'll do it in the future but without ETA.

**Comment by DoubangoTelecom** [comment]
I have checked with my colleagues. It may take months before releasing the Tesseract model because of the #coronavirus. If this doesn't match your deadline you can consider using our Tensorflow models but they are not free/opensouce -> https://www.doubango.org/webapps/micr/

**Comment by haytham90-z** [comment]
Mmm.ok .. 
can I do it by my slef?  .. if can , How can I do it ??

I need it as fast as possible , becuse  I worked on a project that use cmc_7 model

**Comment by haytham90-z** [comment]
iam using cordova model. and i used tesseract blugins  (ocr.text) to read cmc 7 . so i dont need Tensorflow  models

**Comment by DoubangoTelecom** [comment]
Off course you can do it by yourself. Tesseract is open source with many online resources on how to train a model. You can check tesseract-ocr group for help on how to train cmc7 model.

**Comment by haytham90-z** [comment]
Thank you alot

**Comment by Rahma763** [comment]
> can someone send me a cmc7.traineddata. I really appreciat your help.

**Comment by DoubangoTelecom** [comment]
> > can someone send me a cmc7.traineddata. I really appreciat your help.

There is no CMC-7 traineddata. Only E-13B is released.
